package br.ufal.edu.ic.easy.generation;

import java.io.File;
import java.io.IOException;
import java.util.Random;

/**
 * 
 * @author Luiz Carvalho
 * 
 * Generation XML from C code using srcML(www.srcml.org)
 *
 */
public class GenerationXML {
	
	/**
	 * Return a xml file generated by srcML from C code with CPP.
	 * @param C file
	 * @return XML file
	 * @throws IOException 
	 */
	public File convertsFromC(File file) throws IOException {
		Random random = new Random();
		String pathC = file.getAbsolutePath();
		String pathXML = pathC.replace(".c", random.nextInt(Integer.MAX_VALUE) + ".xml");
		if (new File(pathXML).exists()) return convertsFromC(file);
		try {
			String command = "srcml " + "-l " + "C " + pathC + " -o " + pathXML;
			Process p = Runtime.getRuntime().exec(command);
			p.waitFor();
			File xmlFile = new File(pathXML);
			return xmlFile;
		} catch (IOException | InterruptedException e) {
			e.printStackTrace();
		}
		throw new IOException("We can not used the srmML");
	}
	
}
